<?php

namespace Database\Seeders;

use App\Models\Menu;
use App\Models\MenuLocation;
use App\Models\MenuNodes;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Schema;

class MenuSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Schema::disableForeignKeyConstraints();
        MenuNodes::truncate();
        Menu::truncate();
        MenuLocation::truncate();
        Schema::enableForeignKeyConstraints();
        $locations = [
            [
                'location' => 'header-menu',
                'created_at' => now()->toDateTimeString(),
                'updated_at' => now()->toDateTimeString(),
            ],
            [
                'location' => 'main-menu',
                'created_at' => now()->toDateTimeString(),
                'updated_at' => now()->toDateTimeString()
            ],
            [
                'location' => 'sidebar-menu',
                'created_at' => now()->toDateTimeString(),
                'updated_at' => now()->toDateTimeString()
            ],
            [
                'location' => 'footer-menu',
                'created_at' => now()->toDateTimeString(),
                'updated_at' => now()->toDateTimeString()
            ],
            [
                'location' => 'mobile-menu',
                'created_at' => now()->toDateTimeString(),
                'updated_at' => now()->toDateTimeString()
            ]
        ];
        MenuLocation::insert($locations);
        $menus = [
            [
                'menu_location_id' => MenuLocation::where('location', 'header-menu')->first()->id,
                'name' => 'Header Menu',
                'slug' => 'header-menu',
                'status' => 1,
                'created_at' => now()->toDateTimeString(),
                'updated_at' => now()->toDateTimeString()
            ],
            [
                'menu_location_id' => MenuLocation::where('location', 'main-menu')->first()->id,
                'name' => 'Main Menu',
                'slug' => 'main-menu',
                'status' => 1,
                'created_at' => now()->toDateTimeString(),
                'updated_at' => now()->toDateTimeString()
            ],
            [
                'menu_location_id' => MenuLocation::where('location', 'sidebar-menu')->first()->id,
                'name' => 'Sidebar',
                'slug' => 'sidebar',
                'status' => 1,
                'created_at' => now()->toDateTimeString(),
                'updated_at' => now()->toDateTimeString()
            ],
            [
                'menu_location_id' => MenuLocation::where('location', 'footer-menu')->first()->id,
                'name' => 'Footer',
                'slug' => 'footer',
                'status' => 1,
                'created_at' => now()->toDateTimeString(),
                'updated_at' => now()->toDateTimeString()
            ],
            [
                'menu_location_id' => MenuLocation::where('location', 'mobile-menu')->first()->id,
                'name' => 'Mobile Menu',
                'slug' => 'mobile-menu',
                'status' => 1,
                'created_at' => now()->toDateTimeString(),
                'updated_at' => now()->toDateTimeString()
            ],
            [
                'menu_location_id' => MenuLocation::where('location', 'main-menu')->first()->id,
                'name' => 'Mega Menu 1',
                'slug' => 'mega-menu-1',
                'status' => 1,
                'created_at' => now()->toDateTimeString(),
                'updated_at' => now()->toDateTimeString()
            ],
            [
                'menu_location_id' => MenuLocation::where('location', 'main-menu')->first()->id,
                'name' => 'Mega Menu 2',
                'slug' => 'mega-menu-2',
                'status' => 1,
                'created_at' => now()->toDateTimeString(),
                'updated_at' => now()->toDateTimeString()
            ],
            [
                'menu_location_id' => MenuLocation::where('location', 'main-menu')->first()->id,
                'name' => 'Mega Menu 3',
                'slug' => 'mega-menu-3',
                'status' => 1,
                'created_at' => now()->toDateTimeString(),
                'updated_at' => now()->toDateTimeString()
            ],
            [
                'menu_location_id' => MenuLocation::where('location', 'footer-menu')->first()->id,
                'name' => 'Bottom Footer',
                'slug' => 'bottom-footer',
                'status' => 1,
                'created_at' => now()->toDateTimeString(),
                'updated_at' => now()->toDateTimeString()
            ]
        ];
        Menu::insert($menus);
        $menu_nodes = array(
            array('id' => '1', 'menu_id' => '2', 'parent_id' => '0', 'reference_id' => '1', 'reference_type' => 'App\\Models\\Category', 'title' => 'राजस्थान', 'url' => NULL, 'route_name' => 'category-news', 'icon' => NULL, 'css' => NULL, 'target' => '_self', 'position' => '1', 'has_child' => '1', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '2', 'menu_id' => '2', 'parent_id' => '1', 'reference_id' => '44', 'reference_type' => 'App\\Models\\Category', 'title' => 'कोटा', 'url' => NULL, 'route_name' => 'category-news', 'icon' => NULL, 'css' => NULL, 'target' => '_self', 'position' => '2', 'has_child' => '0', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '3', 'menu_id' => '2', 'parent_id' => '1', 'reference_id' => '42', 'reference_type' => 'App\\Models\\Category', 'title' => 'जोधपुर', 'url' => NULL, 'route_name' => 'category-news', 'icon' => NULL, 'css' => NULL, 'target' => '_self', 'position' => '3', 'has_child' => '0', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '4', 'menu_id' => '2', 'parent_id' => '1', 'reference_id' => '40', 'reference_type' => 'App\\Models\\Category', 'title' => 'झालावाड़', 'url' => NULL, 'route_name' => 'category-news', 'icon' => NULL, 'css' => NULL, 'target' => '_self', 'position' => '4', 'has_child' => '0', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '5', 'menu_id' => '2', 'parent_id' => '1', 'reference_id' => '49', 'reference_type' => 'App\\Models\\Category', 'title' => 'सवाई माधोपुर', 'url' => NULL, 'route_name' => 'category-news', 'icon' => NULL, 'css' => NULL, 'target' => '_self', 'position' => '5', 'has_child' => '0', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '6', 'menu_id' => '2', 'parent_id' => '1', 'reference_id' => '52', 'reference_type' => 'App\\Models\\Category', 'title' => 'श्रीगंगानगर', 'url' => NULL, 'route_name' => 'category-news', 'icon' => NULL, 'css' => NULL, 'target' => '_self', 'position' => '6', 'has_child' => '0', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '7', 'menu_id' => '2', 'parent_id' => '1', 'reference_id' => '53', 'reference_type' => 'App\\Models\\Category', 'title' => 'टोंक', 'url' => NULL, 'route_name' => 'category-news', 'icon' => NULL, 'css' => NULL, 'target' => '_self', 'position' => '7', 'has_child' => '0', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '8', 'menu_id' => '2', 'parent_id' => '1', 'reference_id' => '37', 'reference_type' => 'App\\Models\\Category', 'title' => 'जयपुर', 'url' => NULL, 'route_name' => 'category-news', 'icon' => NULL, 'css' => NULL, 'target' => '_self', 'position' => '8', 'has_child' => '0', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '9', 'menu_id' => '2', 'parent_id' => '0', 'reference_id' => '12', 'reference_type' => 'App\\Models\\Category', 'title' => 'गैजेट', 'url' => NULL, 'route_name' => 'category-news', 'icon' => NULL, 'css' => NULL, 'target' => '_self', 'position' => '11', 'has_child' => '1', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '10', 'menu_id' => '2', 'parent_id' => '0', 'reference_id' => '2', 'reference_type' => 'App\\Models\\Category', 'title' => 'राष्ट्रीय', 'url' => NULL, 'route_name' => 'category-news', 'icon' => NULL, 'css' => NULL, 'target' => '_self', 'position' => '9', 'has_child' => '0', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '11', 'menu_id' => '2', 'parent_id' => '0', 'reference_id' => '3', 'reference_type' => 'App\\Models\\Category', 'title' => 'अंतरराष्ट्रीय', 'url' => NULL, 'route_name' => 'category-news', 'icon' => NULL, 'css' => NULL, 'target' => '_self', 'position' => '10', 'has_child' => '0', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '12', 'menu_id' => '2', 'parent_id' => '9', 'reference_id' => '58', 'reference_type' => 'App\\Models\\Category', 'title' => 'टेक्नोलॉजी', 'url' => NULL, 'route_name' => 'category-news', 'icon' => NULL, 'css' => NULL, 'target' => '_self', 'position' => '12', 'has_child' => '0', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '13', 'menu_id' => '2', 'parent_id' => '9', 'reference_id' => '57', 'reference_type' => 'App\\Models\\Category', 'title' => 'टेब/कंप्यूटर', 'url' => NULL, 'route_name' => 'category-news', 'icon' => NULL, 'css' => NULL, 'target' => '_self', 'position' => '13', 'has_child' => '0', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '14', 'menu_id' => '2', 'parent_id' => '9', 'reference_id' => '56', 'reference_type' => 'App\\Models\\Category', 'title' => 'मोबाइल', 'url' => NULL, 'route_name' => 'category-news', 'icon' => NULL, 'css' => NULL, 'target' => '_self', 'position' => '14', 'has_child' => '0', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '15', 'menu_id' => '2', 'parent_id' => '9', 'reference_id' => '55', 'reference_type' => 'App\\Models\\Category', 'title' => 'ऑटोमोबाइल', 'url' => NULL, 'route_name' => 'category-news', 'icon' => NULL, 'css' => NULL, 'target' => '_self', 'position' => '15', 'has_child' => '0', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '16', 'menu_id' => '2', 'parent_id' => '0', 'reference_id' => '7', 'reference_type' => 'App\\Models\\Category', 'title' => 'मनोरंजन', 'url' => NULL, 'route_name' => 'category-news', 'icon' => NULL, 'css' => NULL, 'target' => '_self', 'position' => '16', 'has_child' => '0', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '17', 'menu_id' => '2', 'parent_id' => '0', 'reference_id' => '8', 'reference_type' => 'App\\Models\\Category', 'title' => 'विडियो', 'url' => NULL, 'route_name' => 'category-news', 'icon' => NULL, 'css' => NULL, 'target' => '_self', 'position' => '17', 'has_child' => '0', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '18', 'menu_id' => '2', 'parent_id' => '0', 'reference_id' => '9', 'reference_type' => 'App\\Models\\Category', 'title' => 'बिजनेस', 'url' => NULL, 'route_name' => 'category-news', 'icon' => NULL, 'css' => NULL, 'target' => '_self', 'position' => '18', 'has_child' => '0', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '19', 'menu_id' => '3', 'parent_id' => '0', 'reference_id' => '1', 'reference_type' => 'App\\Models\\Category', 'title' => 'राजस्थान', 'url' => NULL, 'route_name' => 'category-news', 'icon' => '<i class="fas fa-globe-asia"></i>', 'css' => NULL, 'target' => '_self', 'position' => '13', 'has_child' => '1', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '20', 'menu_id' => '3', 'parent_id' => '19', 'reference_id' => '42', 'reference_type' => 'App\\Models\\Category', 'title' => 'जोधपुर', 'url' => NULL, 'route_name' => 'category-news', 'icon' => NULL, 'css' => NULL, 'target' => '_self', 'position' => '2', 'has_child' => '0', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '21', 'menu_id' => '3', 'parent_id' => '19', 'reference_id' => '41', 'reference_type' => 'App\\Models\\Category', 'title' => 'झुंझुनू', 'url' => NULL, 'route_name' => 'category-news', 'icon' => NULL, 'css' => NULL, 'target' => '_self', 'position' => '3', 'has_child' => '0', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '22', 'menu_id' => '3', 'parent_id' => '19', 'reference_id' => '49', 'reference_type' => 'App\\Models\\Category', 'title' => 'सवाई माधोपुर', 'url' => NULL, 'route_name' => 'category-news', 'icon' => NULL, 'css' => NULL, 'target' => '_self', 'position' => '4', 'has_child' => '0', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '23', 'menu_id' => '3', 'parent_id' => '19', 'reference_id' => '50', 'reference_type' => 'App\\Models\\Category', 'title' => 'सीकर', 'url' => NULL, 'route_name' => 'category-news', 'icon' => NULL, 'css' => NULL, 'target' => '_self', 'position' => '5', 'has_child' => '0', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '24', 'menu_id' => '3', 'parent_id' => '19', 'reference_id' => '52', 'reference_type' => 'App\\Models\\Category', 'title' => 'श्रीगंगानगर', 'url' => NULL, 'route_name' => 'category-news', 'icon' => NULL, 'css' => NULL, 'target' => '_self', 'position' => '6', 'has_child' => '0', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '25', 'menu_id' => '3', 'parent_id' => '19', 'reference_id' => '39', 'reference_type' => 'App\\Models\\Category', 'title' => 'जालौर', 'url' => NULL, 'route_name' => 'category-news', 'icon' => NULL, 'css' => NULL, 'target' => '_self', 'position' => '7', 'has_child' => '0', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '26', 'menu_id' => '3', 'parent_id' => '19', 'reference_id' => '38', 'reference_type' => 'App\\Models\\Category', 'title' => 'जैसलमेर', 'url' => NULL, 'route_name' => 'category-news', 'icon' => NULL, 'css' => NULL, 'target' => '_self', 'position' => '8', 'has_child' => '0', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '27', 'menu_id' => '3', 'parent_id' => '19', 'reference_id' => '37', 'reference_type' => 'App\\Models\\Category', 'title' => 'जयपुर', 'url' => NULL, 'route_name' => 'category-news', 'icon' => NULL, 'css' => NULL, 'target' => '_self', 'position' => '9', 'has_child' => '0', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '28', 'menu_id' => '3', 'parent_id' => '0', 'reference_id' => '14', 'reference_type' => 'App\\Models\\Category', 'title' => 'मूवी मसाला', 'url' => NULL, 'route_name' => 'category-news', 'icon' => '<i class="fas fa-film"></i>', 'css' => NULL, 'target' => '_self', 'position' => '10', 'has_child' => '0', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '29', 'menu_id' => '3', 'parent_id' => '0', 'reference_id' => '15', 'reference_type' => 'App\\Models\\Category', 'title' => 'लाईफ स्टाईल', 'url' => NULL, 'route_name' => 'category-news', 'icon' => '<i class="fas fa-cocktail"></i>', 'css' => NULL, 'target' => '_self', 'position' => '11', 'has_child' => '0', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '30', 'menu_id' => '3', 'parent_id' => '0', 'reference_id' => '18', 'reference_type' => 'App\\Models\\Category', 'title' => 'करियर', 'url' => NULL, 'route_name' => 'category-news', 'icon' => '<i class="fas fa-user-md"></i>', 'css' => NULL, 'target' => '_self', 'position' => '12', 'has_child' => '0', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '31', 'menu_id' => '3', 'parent_id' => '0', 'reference_id' => '11', 'reference_type' => 'App\\Models\\Category', 'title' => 'क्राइम', 'url' => NULL, 'route_name' => 'category-news', 'icon' => '<i class="far fa-bell"></i>', 'css' => NULL, 'target' => '_self', 'position' => '1', 'has_child' => '0', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '32', 'menu_id' => '3', 'parent_id' => '0', 'reference_id' => '2', 'reference_type' => 'App\\Models\\Category', 'title' => 'राष्ट्रीय', 'url' => NULL, 'route_name' => 'category-news', 'icon' => '<i class="fas fa-flag"></i>', 'css' => NULL, 'target' => '_self', 'position' => '14', 'has_child' => '0', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '33', 'menu_id' => '3', 'parent_id' => '0', 'reference_id' => '3', 'reference_type' => 'App\\Models\\Category', 'title' => 'अंतरराष्ट्रीय', 'url' => NULL, 'route_name' => 'category-news', 'icon' => '<i class="fas fa-flag-usa"></i>', 'css' => NULL, 'target' => '_self', 'position' => '15', 'has_child' => '0', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '34', 'menu_id' => '3', 'parent_id' => '0', 'reference_id' => '6', 'reference_type' => 'App\\Models\\Category', 'title' => 'राजनीति', 'url' => NULL, 'route_name' => 'category-news', 'icon' => '<i class="fas fa-fist-raised"></i>', 'css' => NULL, 'target' => '_self', 'position' => '18', 'has_child' => '0', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '35', 'menu_id' => '3', 'parent_id' => '0', 'reference_id' => '7', 'reference_type' => 'App\\Models\\Category', 'title' => 'मनोरंजन', 'url' => NULL, 'route_name' => 'category-news', 'icon' => '<i class="fas fa-theater-masks"></i>', 'css' => NULL, 'target' => '_self', 'position' => '17', 'has_child' => '0', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '36', 'menu_id' => '3', 'parent_id' => '0', 'reference_id' => '12', 'reference_type' => 'App\\Models\\Category', 'title' => 'गैजेट', 'url' => NULL, 'route_name' => 'category-news', 'icon' => '<i class="fas fa-mobile-alt"></i>', 'css' => NULL, 'target' => '_self', 'position' => '16', 'has_child' => '1', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '37', 'menu_id' => '3', 'parent_id' => '36', 'reference_id' => '58', 'reference_type' => 'App\\Models\\Category', 'title' => 'टेक्नोलॉजी', 'url' => NULL, 'route_name' => 'category-news', 'icon' => '<i class="fas fa-microchip"></i>', 'css' => NULL, 'target' => '_self', 'position' => '19', 'has_child' => '0', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '38', 'menu_id' => '3', 'parent_id' => '36', 'reference_id' => '57', 'reference_type' => 'App\\Models\\Category', 'title' => 'टेब/कंप्यूटर', 'url' => NULL, 'route_name' => 'category-news', 'icon' => NULL, 'css' => NULL, 'target' => '_self', 'position' => '20', 'has_child' => '0', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '39', 'menu_id' => '3', 'parent_id' => '36', 'reference_id' => '56', 'reference_type' => 'App\\Models\\Category', 'title' => 'मोबाइल', 'url' => NULL, 'route_name' => 'category-news', 'icon' => NULL, 'css' => NULL, 'target' => '_self', 'position' => '21', 'has_child' => '0', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '40', 'menu_id' => '3', 'parent_id' => '36', 'reference_id' => '55', 'reference_type' => 'App\\Models\\Category', 'title' => 'ऑटोमोबाइल', 'url' => NULL, 'route_name' => 'category-news', 'icon' => NULL, 'css' => NULL, 'target' => '_self', 'position' => '22', 'has_child' => '0', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '41', 'menu_id' => '5', 'parent_id' => '0', 'reference_id' => '1', 'reference_type' => 'App\\Models\\Category', 'title' => 'राजस्थान', 'url' => NULL, 'route_name' => 'category-news', 'icon' => NULL, 'css' => NULL, 'target' => '_self', 'position' => '1', 'has_child' => '0', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '42', 'menu_id' => '5', 'parent_id' => '0', 'reference_id' => '13', 'reference_type' => 'App\\Models\\Category', 'title' => 'सोशल मीडिया', 'url' => NULL, 'route_name' => 'category-news', 'icon' => NULL, 'css' => NULL, 'target' => '_self', 'position' => '2', 'has_child' => '0', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '43', 'menu_id' => '5', 'parent_id' => '0', 'reference_id' => '14', 'reference_type' => 'App\\Models\\Category', 'title' => 'मूवी मसाला', 'url' => NULL, 'route_name' => 'category-news', 'icon' => NULL, 'css' => NULL, 'target' => '_self', 'position' => '3', 'has_child' => '0', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '44', 'menu_id' => '5', 'parent_id' => '0', 'reference_id' => '15', 'reference_type' => 'App\\Models\\Category', 'title' => 'लाईफ स्टाईल', 'url' => NULL, 'route_name' => 'category-news', 'icon' => NULL, 'css' => NULL, 'target' => '_self', 'position' => '4', 'has_child' => '0', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '45', 'menu_id' => '5', 'parent_id' => '0', 'reference_id' => '16', 'reference_type' => 'App\\Models\\Category', 'title' => 'स्त्री', 'url' => NULL, 'route_name' => 'category-news', 'icon' => NULL, 'css' => NULL, 'target' => '_self', 'position' => '5', 'has_child' => '0', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '46', 'menu_id' => '5', 'parent_id' => '0', 'reference_id' => '17', 'reference_type' => 'App\\Models\\Category', 'title' => 'धर्म', 'url' => NULL, 'route_name' => 'category-news', 'icon' => NULL, 'css' => NULL, 'target' => '_self', 'position' => '6', 'has_child' => '0', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '47', 'menu_id' => '5', 'parent_id' => '0', 'reference_id' => '18', 'reference_type' => 'App\\Models\\Category', 'title' => 'करियर', 'url' => NULL, 'route_name' => 'category-news', 'icon' => NULL, 'css' => NULL, 'target' => '_self', 'position' => '7', 'has_child' => '0', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '48', 'menu_id' => '5', 'parent_id' => '0', 'reference_id' => '19', 'reference_type' => 'App\\Models\\Category', 'title' => 'नॉलेज न्यूज़', 'url' => NULL, 'route_name' => 'category-news', 'icon' => NULL, 'css' => NULL, 'target' => '_self', 'position' => '8', 'has_child' => '0', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '49', 'menu_id' => '5', 'parent_id' => '0', 'reference_id' => '20', 'reference_type' => 'App\\Models\\Category', 'title' => 'अन्य ख़बरे', 'url' => NULL, 'route_name' => 'category-news', 'icon' => NULL, 'css' => NULL, 'target' => '_self', 'position' => '9', 'has_child' => '0', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '80', 'menu_id' => '4', 'parent_id' => '0', 'reference_id' => NULL, 'reference_type' => NULL, 'title' => 'LATEST NEWS', 'url' => 'javascript:void(0)', 'route_name' => 'custom-link', 'icon' => '', 'css' => '', 'target' => '_self', 'position' => '0', 'has_child' => '1', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '81', 'menu_id' => '4', 'parent_id' => '80', 'reference_id' => '11', 'reference_type' => 'App\\Models\\Category', 'title' => 'Crime News', 'url' => NULL, 'route_name' => 'category-news', 'icon' => '', 'css' => '', 'target' => '_self', 'position' => '0', 'has_child' => '0', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '82', 'menu_id' => '4', 'parent_id' => '80', 'reference_id' => '5', 'reference_type' => 'App\\Models\\Category', 'title' => 'Covid-19 News', 'url' => NULL, 'route_name' => 'category-news', 'icon' => '', 'css' => '', 'target' => '_self', 'position' => '1', 'has_child' => '0', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '83', 'menu_id' => '4', 'parent_id' => '80', 'reference_id' => '6', 'reference_type' => 'App\\Models\\Category', 'title' => 'Political News', 'url' => NULL, 'route_name' => 'category-news', 'icon' => '', 'css' => '', 'target' => '_self', 'position' => '2', 'has_child' => '0', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '84', 'menu_id' => '4', 'parent_id' => '80', 'reference_id' => '2', 'reference_type' => 'App\\Models\\Category', 'title' => 'National News', 'url' => NULL, 'route_name' => 'category-news', 'icon' => '', 'css' => '', 'target' => '_self', 'position' => '3', 'has_child' => '0', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '86', 'menu_id' => '4', 'parent_id' => '80', 'reference_id' => '19', 'reference_type' => 'App\\Models\\Category', 'title' => 'Knowledged News', 'url' => NULL, 'route_name' => 'category-news', 'icon' => '', 'css' => '', 'target' => '_self', 'position' => '4', 'has_child' => '0', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '87', 'menu_id' => '4', 'parent_id' => '80', 'reference_id' => '17', 'reference_type' => 'App\\Models\\Category', 'title' => 'Religion News', 'url' => NULL, 'route_name' => 'category-news', 'icon' => '', 'css' => '', 'target' => '_self', 'position' => '5', 'has_child' => '0', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '88', 'menu_id' => '4', 'parent_id' => '80', 'reference_id' => '13', 'reference_type' => 'App\\Models\\Category', 'title' => 'Social Media News', 'url' => NULL, 'route_name' => 'category-news', 'icon' => '', 'css' => '', 'target' => '_self', 'position' => '8', 'has_child' => '0', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '89', 'menu_id' => '4', 'parent_id' => '80', 'reference_id' => '18', 'reference_type' => 'App\\Models\\Category', 'title' => 'Career News', 'url' => NULL, 'route_name' => 'category-news', 'icon' => '', 'css' => '', 'target' => '_self', 'position' => '7', 'has_child' => '0', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '90', 'menu_id' => '4', 'parent_id' => '80', 'reference_id' => '10', 'reference_type' => 'App\\Models\\Category', 'title' => 'Sport News', 'url' => NULL, 'route_name' => 'category-news', 'icon' => '', 'css' => '', 'target' => '_self', 'position' => '6', 'has_child' => '0', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '91', 'menu_id' => '4', 'parent_id' => '0', 'reference_id' => NULL, 'reference_type' => NULL, 'title' => 'LIFE STYLE', 'url' => 'javascript:void(0)', 'route_name' => 'custom-link', 'icon' => NULL, 'css' => NULL, 'target' => '_self', 'position' => '11', 'has_child' => '0', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '92', 'menu_id' => '7', 'parent_id' => '0', 'reference_id' => '1', 'reference_type' => 'App\\Models\\Category', 'title' => 'राजस्थान', 'url' => NULL, 'route_name' => 'category-news', 'icon' => '', 'css' => '', 'target' => '_self', 'position' => '0', 'has_child' => '1', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '93', 'menu_id' => '7', 'parent_id' => '92', 'reference_id' => '51', 'reference_type' => 'App\\Models\\Category', 'title' => 'सिरोही', 'url' => NULL, 'route_name' => 'category-news', 'icon' => '', 'css' => '', 'target' => '_self', 'position' => '0', 'has_child' => '0', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '94', 'menu_id' => '7', 'parent_id' => '92', 'reference_id' => '52', 'reference_type' => 'App\\Models\\Category', 'title' => 'श्रीगंगानगर', 'url' => NULL, 'route_name' => 'category-news', 'icon' => '', 'css' => '', 'target' => '_self', 'position' => '1', 'has_child' => '0', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '95', 'menu_id' => '7', 'parent_id' => '92', 'reference_id' => '53', 'reference_type' => 'App\\Models\\Category', 'title' => 'टोंक', 'url' => NULL, 'route_name' => 'category-news', 'icon' => '', 'css' => '', 'target' => '_self', 'position' => '2', 'has_child' => '0', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '96', 'menu_id' => '7', 'parent_id' => '92', 'reference_id' => '54', 'reference_type' => 'App\\Models\\Category', 'title' => 'उदयपुर', 'url' => NULL, 'route_name' => 'category-news', 'icon' => '', 'css' => '', 'target' => '_self', 'position' => '3', 'has_child' => '0', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '97', 'menu_id' => '7', 'parent_id' => '92', 'reference_id' => '38', 'reference_type' => 'App\\Models\\Category', 'title' => 'जैसलमेर', 'url' => NULL, 'route_name' => 'category-news', 'icon' => '', 'css' => '', 'target' => '_self', 'position' => '4', 'has_child' => '0', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '98', 'menu_id' => '7', 'parent_id' => '92', 'reference_id' => '37', 'reference_type' => 'App\\Models\\Category', 'title' => 'जयपुर', 'url' => NULL, 'route_name' => 'category-news', 'icon' => '', 'css' => '', 'target' => '_self', 'position' => '5', 'has_child' => '0', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '99', 'menu_id' => '7', 'parent_id' => '92', 'reference_id' => '22', 'reference_type' => 'App\\Models\\Category', 'title' => 'अजमेर', 'url' => NULL, 'route_name' => 'category-news', 'icon' => '', 'css' => '', 'target' => '_self', 'position' => '6', 'has_child' => '0', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '100', 'menu_id' => '7', 'parent_id' => '92', 'reference_id' => '23', 'reference_type' => 'App\\Models\\Category', 'title' => 'अलवर', 'url' => NULL, 'route_name' => 'category-news', 'icon' => '', 'css' => '', 'target' => '_self', 'position' => '7', 'has_child' => '0', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '101', 'menu_id' => '7', 'parent_id' => '92', 'reference_id' => '24', 'reference_type' => 'App\\Models\\Category', 'title' => 'बांसवाड़ा', 'url' => NULL, 'route_name' => 'category-news', 'icon' => '', 'css' => '', 'target' => '_self', 'position' => '8', 'has_child' => '0', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '102', 'menu_id' => '7', 'parent_id' => '92', 'reference_id' => '25', 'reference_type' => 'App\\Models\\Category', 'title' => 'बारां', 'url' => NULL, 'route_name' => 'category-news', 'icon' => '', 'css' => '', 'target' => '_self', 'position' => '9', 'has_child' => '0', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '103', 'menu_id' => '6', 'parent_id' => '0', 'reference_id' => '15', 'reference_type' => 'App\\Models\\Category', 'title' => 'लाईफ स्टाईल', 'url' => NULL, 'route_name' => 'category-news', 'icon' => '', 'css' => '', 'target' => '_self', 'position' => '0', 'has_child' => '1', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '104', 'menu_id' => '6', 'parent_id' => '103', 'reference_id' => '67', 'reference_type' => 'App\\Models\\Category', 'title' => 'रिलेशनशिप', 'url' => NULL, 'route_name' => 'category-news', 'icon' => '', 'css' => '', 'target' => '_self', 'position' => '0', 'has_child' => '1', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '105', 'menu_id' => '6', 'parent_id' => '103', 'reference_id' => '65', 'reference_type' => 'App\\Models\\Category', 'title' => 'फिटनेस', 'url' => NULL, 'route_name' => 'category-news', 'icon' => '', 'css' => '', 'target' => '_self', 'position' => '1', 'has_child' => '1', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '106', 'menu_id' => '6', 'parent_id' => '103', 'reference_id' => '64', 'reference_type' => 'App\\Models\\Category', 'title' => 'पैसो की बात', 'url' => NULL, 'route_name' => 'category-news', 'icon' => '', 'css' => '', 'target' => '_self', 'position' => '2', 'has_child' => '1', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '107', 'menu_id' => '6', 'parent_id' => '103', 'reference_id' => '63', 'reference_type' => 'App\\Models\\Category', 'title' => 'पर्यटन', 'url' => NULL, 'route_name' => 'category-news', 'icon' => '', 'css' => '', 'target' => '_self', 'position' => '3', 'has_child' => '1', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '108', 'menu_id' => '6', 'parent_id' => '103', 'reference_id' => '66', 'reference_type' => 'App\\Models\\Category', 'title' => 'राईट डाईट', 'url' => NULL, 'route_name' => 'category-news', 'icon' => '', 'css' => '', 'target' => '_self', 'position' => '4', 'has_child' => '1', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '109', 'menu_id' => '6', 'parent_id' => '104', 'reference_id' => '5', 'reference_type' => 'App\\Models\\Category', 'title' => 'कोरोना', 'url' => NULL, 'route_name' => 'category-news', 'icon' => '', 'css' => '', 'target' => '_self', 'position' => '0', 'has_child' => '0', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '110', 'menu_id' => '6', 'parent_id' => '104', 'reference_id' => '6', 'reference_type' => 'App\\Models\\Category', 'title' => 'राजनीति', 'url' => NULL, 'route_name' => 'category-news', 'icon' => '', 'css' => '', 'target' => '_self', 'position' => '1', 'has_child' => '0', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '111', 'menu_id' => '6', 'parent_id' => '104', 'reference_id' => '7', 'reference_type' => 'App\\Models\\Category', 'title' => 'मनोरंजन', 'url' => NULL, 'route_name' => 'category-news', 'icon' => '', 'css' => '', 'target' => '_self', 'position' => '2', 'has_child' => '0', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '112', 'menu_id' => '6', 'parent_id' => '104', 'reference_id' => '8', 'reference_type' => 'App\\Models\\Category', 'title' => 'विडियो', 'url' => NULL, 'route_name' => 'category-news', 'icon' => '', 'css' => '', 'target' => '_self', 'position' => '3', 'has_child' => '0', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '113', 'menu_id' => '6', 'parent_id' => '104', 'reference_id' => '9', 'reference_type' => 'App\\Models\\Category', 'title' => 'बिजनेस', 'url' => NULL, 'route_name' => 'category-news', 'icon' => '', 'css' => '', 'target' => '_self', 'position' => '4', 'has_child' => '0', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '114', 'menu_id' => '6', 'parent_id' => '105', 'reference_id' => '7', 'reference_type' => 'App\\Models\\Category', 'title' => 'मनोरंजन', 'url' => NULL, 'route_name' => 'category-news', 'icon' => '', 'css' => '', 'target' => '_self', 'position' => '0', 'has_child' => '0', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '115', 'menu_id' => '6', 'parent_id' => '105', 'reference_id' => '8', 'reference_type' => 'App\\Models\\Category', 'title' => 'विडियो', 'url' => NULL, 'route_name' => 'category-news', 'icon' => '', 'css' => '', 'target' => '_self', 'position' => '1', 'has_child' => '0', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '116', 'menu_id' => '6', 'parent_id' => '105', 'reference_id' => '9', 'reference_type' => 'App\\Models\\Category', 'title' => 'बिजनेस', 'url' => NULL, 'route_name' => 'category-news', 'icon' => '', 'css' => '', 'target' => '_self', 'position' => '2', 'has_child' => '0', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '117', 'menu_id' => '6', 'parent_id' => '105', 'reference_id' => '10', 'reference_type' => 'App\\Models\\Category', 'title' => 'खेल', 'url' => NULL, 'route_name' => 'category-news', 'icon' => '', 'css' => '', 'target' => '_self', 'position' => '3', 'has_child' => '0', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '118', 'menu_id' => '6', 'parent_id' => '105', 'reference_id' => '45', 'reference_type' => 'App\\Models\\Category', 'title' => 'नागौर', 'url' => NULL, 'route_name' => 'category-news', 'icon' => '', 'css' => '', 'target' => '_self', 'position' => '4', 'has_child' => '0', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '119', 'menu_id' => '6', 'parent_id' => '106', 'reference_id' => '35', 'reference_type' => 'App\\Models\\Category', 'title' => 'डूंगरपुर', 'url' => NULL, 'route_name' => 'category-news', 'icon' => '', 'css' => '', 'target' => '_self', 'position' => '1', 'has_child' => '0', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '120', 'menu_id' => '6', 'parent_id' => '106', 'reference_id' => '36', 'reference_type' => 'App\\Models\\Category', 'title' => 'हनुमानगढ़', 'url' => NULL, 'route_name' => 'category-news', 'icon' => '', 'css' => '', 'target' => '_self', 'position' => '0', 'has_child' => '0', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '121', 'menu_id' => '6', 'parent_id' => '106', 'reference_id' => '58', 'reference_type' => 'App\\Models\\Category', 'title' => 'टेक्नोलॉजी', 'url' => NULL, 'route_name' => 'category-news', 'icon' => '', 'css' => '', 'target' => '_self', 'position' => '2', 'has_child' => '0', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '122', 'menu_id' => '6', 'parent_id' => '106', 'reference_id' => '57', 'reference_type' => 'App\\Models\\Category', 'title' => 'टेब/कंप्यूटर', 'url' => NULL, 'route_name' => 'category-news', 'icon' => '', 'css' => '', 'target' => '_self', 'position' => '3', 'has_child' => '0', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '123', 'menu_id' => '6', 'parent_id' => '106', 'reference_id' => '56', 'reference_type' => 'App\\Models\\Category', 'title' => 'मोबाइल', 'url' => NULL, 'route_name' => 'category-news', 'icon' => '', 'css' => '', 'target' => '_self', 'position' => '4', 'has_child' => '0', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '124', 'menu_id' => '6', 'parent_id' => '107', 'reference_id' => '80', 'reference_type' => 'App\\Models\\Category', 'title' => 'कला', 'url' => NULL, 'route_name' => 'category-news', 'icon' => '', 'css' => '', 'target' => '_self', 'position' => '1', 'has_child' => '0', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '125', 'menu_id' => '6', 'parent_id' => '107', 'reference_id' => '83', 'reference_type' => 'App\\Models\\Category', 'title' => 'मोसम', 'url' => NULL, 'route_name' => 'category-news', 'icon' => '', 'css' => '', 'target' => '_self', 'position' => '0', 'has_child' => '0', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '126', 'menu_id' => '6', 'parent_id' => '107', 'reference_id' => '84', 'reference_type' => 'App\\Models\\Category', 'title' => 'कार्यक्रम', 'url' => NULL, 'route_name' => 'category-news', 'icon' => '', 'css' => '', 'target' => '_self', 'position' => '2', 'has_child' => '0', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '127', 'menu_id' => '6', 'parent_id' => '107', 'reference_id' => '85', 'reference_type' => 'App\\Models\\Category', 'title' => 'दुर्घटना', 'url' => NULL, 'route_name' => 'category-news', 'icon' => '', 'css' => '', 'target' => '_self', 'position' => '3', 'has_child' => '0', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '128', 'menu_id' => '6', 'parent_id' => '107', 'reference_id' => '79', 'reference_type' => 'App\\Models\\Category', 'title' => 'शिक्षा', 'url' => NULL, 'route_name' => 'category-news', 'icon' => '', 'css' => '', 'target' => '_self', 'position' => '4', 'has_child' => '0', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '129', 'menu_id' => '6', 'parent_id' => '108', 'reference_id' => '86', 'reference_type' => 'App\\Models\\Category', 'title' => 'गूगल न्यूज़', 'url' => NULL, 'route_name' => 'category-news', 'icon' => '', 'css' => '', 'target' => '_self', 'position' => '0', 'has_child' => '0', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '130', 'menu_id' => '6', 'parent_id' => '108', 'reference_id' => '87', 'reference_type' => 'App\\Models\\Category', 'title' => 'फेसबुक न्यूज़', 'url' => NULL, 'route_name' => 'category-news', 'icon' => '', 'css' => '', 'target' => '_self', 'position' => '1', 'has_child' => '0', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '131', 'menu_id' => '6', 'parent_id' => '108', 'reference_id' => '88', 'reference_type' => 'App\\Models\\Category', 'title' => 'ट्विटर न्यूज़', 'url' => NULL, 'route_name' => 'category-news', 'icon' => '', 'css' => '', 'target' => '_self', 'position' => '2', 'has_child' => '0', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '132', 'menu_id' => '6', 'parent_id' => '108', 'reference_id' => '89', 'reference_type' => 'App\\Models\\Category', 'title' => 'यूट्यूब न्यूज़', 'url' => NULL, 'route_name' => 'category-news', 'icon' => '', 'css' => '', 'target' => '_self', 'position' => '3', 'has_child' => '0', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '133', 'menu_id' => '6', 'parent_id' => '108', 'reference_id' => '61', 'reference_type' => 'App\\Models\\Category', 'title' => 'बर्थ स्पेशल', 'url' => NULL, 'route_name' => 'category-news', 'icon' => '', 'css' => '', 'target' => '_self', 'position' => '4', 'has_child' => '0', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '134', 'menu_id' => '6', 'parent_id' => '103', 'reference_id' => '82', 'reference_type' => 'App\\Models\\Category', 'title' => 'खोज', 'url' => NULL, 'route_name' => 'category-news', 'icon' => '', 'css' => '', 'target' => '_self', 'position' => '5', 'has_child' => '1', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '135', 'menu_id' => '6', 'parent_id' => '134', 'reference_id' => '81', 'reference_type' => 'App\\Models\\Category', 'title' => 'कृषि', 'url' => NULL, 'route_name' => 'category-news', 'icon' => '', 'css' => '', 'target' => '_self', 'position' => '0', 'has_child' => '0', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '136', 'menu_id' => '6', 'parent_id' => '134', 'reference_id' => '80', 'reference_type' => 'App\\Models\\Category', 'title' => 'कला', 'url' => NULL, 'route_name' => 'category-news', 'icon' => '', 'css' => '', 'target' => '_self', 'position' => '1', 'has_child' => '0', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '137', 'menu_id' => '6', 'parent_id' => '134', 'reference_id' => '83', 'reference_type' => 'App\\Models\\Category', 'title' => 'मोसम', 'url' => NULL, 'route_name' => 'category-news', 'icon' => '', 'css' => '', 'target' => '_self', 'position' => '2', 'has_child' => '0', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '138', 'menu_id' => '6', 'parent_id' => '134', 'reference_id' => '84', 'reference_type' => 'App\\Models\\Category', 'title' => 'कार्यक्रम', 'url' => NULL, 'route_name' => 'category-news', 'icon' => '', 'css' => '', 'target' => '_self', 'position' => '3', 'has_child' => '0', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '139', 'menu_id' => '6', 'parent_id' => '134', 'reference_id' => '85', 'reference_type' => 'App\\Models\\Category', 'title' => 'दुर्घटना', 'url' => NULL, 'route_name' => 'category-news', 'icon' => '', 'css' => '', 'target' => '_self', 'position' => '4', 'has_child' => '0', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '140', 'menu_id' => '8', 'parent_id' => '0', 'reference_id' => '81', 'reference_type' => 'App\\Models\\Category', 'title' => 'कृषि', 'url' => NULL, 'route_name' => 'category-news', 'icon' => NULL, 'css' => NULL, 'target' => '_self', 'position' => '1', 'has_child' => '0', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '141', 'menu_id' => '9', 'parent_id' => '0', 'reference_id' => NULL, 'reference_type' => NULL, 'title' => 'ABOUT US', 'url' => 'javascript:void(0)', 'route_name' => 'custom-link', 'icon' => '', 'css' => '', 'target' => '_self', 'position' => '0', 'has_child' => '0', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '147', 'menu_id' => '9', 'parent_id' => '0', 'reference_id' => NULL, 'reference_type' => NULL, 'title' => 'CONTACT US', 'url' => 'javascript:void(0)', 'route_name' => 'custom-link', 'icon' => '', 'css' => '', 'target' => '_self', 'position' => '5', 'has_child' => '0', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '149', 'menu_id' => '9', 'parent_id' => '0', 'reference_id' => NULL, 'reference_type' => NULL, 'title' => 'FEEDBACK', 'url' => 'javascript:void(0)', 'route_name' => 'custom-link', 'icon' => '', 'css' => '', 'target' => '_self', 'position' => '2', 'has_child' => '0', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '150', 'menu_id' => '9', 'parent_id' => '0', 'reference_id' => NULL, 'reference_type' => NULL, 'title' => 'CAREERS', 'url' => 'javascript:void(0)', 'route_name' => 'custom-link', 'icon' => '', 'css' => '', 'target' => '_self', 'position' => '1', 'has_child' => '0', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '151', 'menu_id' => '9', 'parent_id' => '0', 'reference_id' => NULL, 'reference_type' => NULL, 'title' => 'ADVERTISMENT WITH US', 'url' => 'javascript:void(0)', 'route_name' => 'custom-link', 'icon' => '', 'css' => '', 'target' => '_self', 'position' => '3', 'has_child' => '0', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '152', 'menu_id' => '9', 'parent_id' => '0', 'reference_id' => NULL, 'reference_type' => NULL, 'title' => 'SITEMAP', 'url' => 'javascript:void(0)', 'route_name' => 'custom-link', 'icon' => '', 'css' => '', 'target' => '_self', 'position' => '4', 'has_child' => '0', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '153', 'menu_id' => '9', 'parent_id' => '0', 'reference_id' => NULL, 'reference_type' => NULL, 'title' => 'PRIVACY POLICY', 'url' => 'javascript:void(0)', 'route_name' => 'custom-link', 'icon' => '', 'css' => '', 'target' => '_self', 'position' => '6', 'has_child' => '0', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString()),
            array('id' => '154', 'menu_id' => '9', 'parent_id' => '0', 'reference_id' => NULL, 'reference_type' => NULL, 'title' => 'DISCLAMER', 'url' => 'javascript:void(0)', 'route_name' => 'custom-link', 'icon' => '', 'css' => '', 'target' => '_self', 'position' => '7', 'has_child' => '0', 'created_at' => now()->toDateTimeString(), 'updated_at' => now()->toDateTimeString())
        );
        $nodes = array_chunk($menu_nodes, 10);
        foreach ($nodes as $node) {
            MenuNodes::insert($node);
        }
    }
}
