name: News15India Deploy Production
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  web-deploy:
    name: Deploying...
    runs-on: ubuntu-latest
    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'
    - uses: actions/checkout@v2.3.2
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer update --no-dev --no-interaction --prefer-dist --optimize-autoloader
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: 📂 Sync files
      uses: News15India/ssh-Deploy-Action@4.0.0
      with:
        server: '217.21.91.22'
        username: 'u845004101'
        password: 'Aashish@123'
        server_dir: /home/u845004101/domains/news15india.com/
